# 로컬 데이터베이스에서 개발 시 사용(datasource의 요소를 자신의 로컬 환경에 맞게 수정하세요.)
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/monghyang?useUnicode=true&characterEncoding=utf8
    username: monghyang
    password: Query1234!
    driver-class-name: org.mariadb.jdbc.Driver
    # 커넥션 풀 개수 설정
    hikari:
      pool-name: HikariCP
      maximum-pool-size: 10
  config:
    import: optional:classpath:/.env[.properties] # .env 파일의 환경변수를 주입하여 빌드(실행)
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 6s
      lettuce:
        pool:
          max-active: 10 # 최대 redis 커넥션 개수
          max-idle: 5 # 유휴 커넥션 최대 개수
          min-idle: 1 # 유휴 커넥션 최소 개수
      password: Qwerty1234! # redis 비밀번호
      username: default

app:
  client-url: http://localhost:3000 # 클라이언트 url
#  storage-path:  # 스토리지 '시작' 경로
  cookie-samesite: None
  cookie-domain: localhost