# FE 팀 로컬 테스트 시 사용
spring:
  datasource:
    url: ${RDS_URL}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate # 개발 시에는 'create' or 'update', 실제 운영 시 'validate' or 'none'
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  config:
    import: optional:file:./.env[.properties] # .env 파일의 환경변수를 주입하여 jar 실행
  flyway:
    baseline-on-migrate: true        # 기존 스키마를 baseline 처리
app:
  client-url: http://localhost:3000,https://www.monghyang.com,https://admin.monghyang.com,https://test.monghyang.com
  s3:
    bucket: monghyang-image-store
    region: ap-northeast-2
    presign-exp-minutes: 5
server:
  port: 61234