# 정식 배포 시 사용
spring:
  datasource:
    url: ${RDS_URL}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none  # 개발 시에는 'create' or 'update', 실제 운영 시 'validate' or 'none'
  config:
    import: optional:file:./.env[.properties] # .env 파일의 환경변수를 주입하여 jar 실행
  flyway:
    baseline-on-migrate: true        # 기존 스키마를 baseline 처리
app:
  client-url: https://www.monghyang.com # 실제 운영 도메인 url origin
  s3:
    bucket: monghyang-image-store
    region: ap-northeast-2
    presign-exp-minutes: 5
server:
  port: 61234