# FE 팀 로컬 테스트 시 사용
spring:
  datasource:
    url: ${RDS_URL}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update # 개발 시에는 'create' or 'update', 실제 운영 시 'validate' or 'none'
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  config:
    import: optional:file:./.env[.properties] # .env 파일의 환경변수를 주입하여 jar 실행
app:
  client-url: http://localhost:3000 # 클라이언트 url
  s3:
    bucket: monghyang-image-store
    region: ap-northeast-2
    presign-exp-minutes: 5
server:
  port: 61234